### ISSUE TITLE
Queue code invitation

### ISSUE THREAD

**Issue by SMore-Napi** [InnoQueue/Backend#1]
Create new **GET** request which creates a new unique temporary queue pin-code and QR-code. 
- Pin code will be automatically destroyed after 60 mins and it's length is 6 digits.
- QR code will be automatically destroyed after 24 hours and it's length is 48 symbols.

## Tasks
- [x] delete `link` field
- [x] add `pin_code` field 
- [x] add `qr_code` field
